#
# This is free software, license use MIT.
# 
# Copyright (C) 2021 smallprogram <smallprogramzhusir@gmail.com>
# 

name: Merge-upstream
permissions:
  contents: write
  workflows: write
on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  push:
    branches: 
      - master
  schedule:
    - cron: 0 */2 * * *
    
jobs:

  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run: |
        git config --global user.email "${{ github.actor }}@foxmail.com"
        git config --global user.name "${{ github.actor }}"

    - name: Sync upstream
      run: |
        git fetch https://github.com/smallprogram/OpenWrtAction.git main
        git reset --hard FETCH_HEAD
        git clean -fdx

    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: ${{ github.ref }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        git push origin $DOWNSTREAM_BRANCH --force

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 4
